### PR TITLE
Packaging up the algorithmic shrinking code as a WIP

### PR DESCRIPTION
**Pull request by ublubu**
It's under its own subcommand and it's not required by any other packages, so it won't break anything.

It works, and it's in a good place to iterate on, but it definitely needs work.

### CODE REVIEW

**Comment by wlan0** [comment]
Fix the commit messages. They are meaningless

**Comment by ublubu** [comment]
done @wlan0

**Comment by wlan0** [comment]
Thanks @ublubu.

We need to figure out the a clean way to present this to users. But for now LGTM.

**Comment by wlan0** [comment]
Why'd you merge this? This is a WIP. I know this code is great, but this should be its own branch. Not a part of the main product. Please revert this right away.

**Comment by ublubu** [comment]
oh shoot, i thought the LGTM meant to merge.

**Pull request merged**
